p = [
    "Fiji",
    "Sierra Leone",
    "Bulgaria",
    "Chad",
    "Cocos (Keeling) Islands",
    "Malta",
    "Montenegro",
    "Tanzania, United Republic of",
    "Nepal",
    "Turkey",
    "Cuba",
    "Hungary",
    "Cameroon",
    "Swaziland",
    "Uruguay",
    "Vanuatu",
    "Bermuda",
    "South Sudan",
    "Guatemala",
    "Iran, Islamic Republic of",
    "Madagascar",
    "Switzerland",
    "Cyprus",
    "Estonia",
    "Egypt",
    "Timor-Leste",
    "New Caledonia",
    "Rwanda",
    "Barbados",
    "Bhutan",
    "Israel",
    "Saint Helena",
    "Ukraine",
    "United Kingdom",
    "Uzbekistan",
    "Cook Islands",
    "Kyrgyzstan",
    "Morocco",
    "Norfolk Island",
    "Sudan",
    "Eritrea",
    "Liechtenstein",
    "Cambodia",
    "Niue",
    "Argentina",
    "Botswana",
    "Tonga",
    "Guernsey",
    "Kenya",
    "Saint Lucia",
    "Lebanon",
    "Mozambique",
    "Jordan",
    "Saint-Barth\u00e9lemy",
    "British Indian Ocean Territory",
    "Guinea-Bissau",
    "Montserrat",
    "Yemen",
    "Congo (Kinshasa)",
    "Ireland",
    "Martinique",
    "Canada",
    "Micronesia, Federated States of",
    "Netherlands",
    "Portugal",
    "Thailand",
    "US Minor Outlying Islands",
    "Bolivia",
    "Ethiopia",
    "French Southern Territories",
    "Nicaragua",
    "Niger",
    "Viet Nam",
    "Belarus",
    "Netherlands Antilles",
    "South Georgia and the South Sandwich Islands",
    "Indonesia",
    "Northern Mariana Islands",
    "Panama",
    "Saint Vincent and Grenadines",
    "Denmark",
    "India",
    "Brazil",
    "Uganda",
    "Mexico",
    "Palestinian Territory",
    "Svalbard and Jan Mayen Islands",
    "Honduras",
    "Mauritius",
    "Aruba",
    "Lao PDR",
    "Croatia",
    "Grenada",
    "Liberia",
    "Slovakia",
    "Algeria",
    "Bahrain",
    "Suriname",
    "Antigua and Barbuda",
    "Armenia",
    "Faroe Islands",
    "Cape Verde",
    "Malaysia",
    "Bosnia and Herzegovina",
    "Ghana",
    "Nigeria",
    "Greenland",
    "Togo",
    "Trinidad and Tobago",
    "R\u00e9union",
    "Jamaica",
    "Maldives",
    "Costa Rica",
    "Finland",
    "Isle of Man",
    "Antarctica",
    "Cayman Islands",
    "Guadeloupe",
    "Hong Kong, SAR China",
    "Kuwait",
    "Andorra",
    "Poland",
    "Saudi Arabia",
    "Slovenia",
    "Afghanistan",
    "Libya",
    "Oman",
    "United States of America",
    "Bouvet Island",
    "Germany",
    "Paraguay",
    "Mayotte",
    "Namibia",
    "Somalia",
    "Wallis and Futuna Islands",
    "Georgia",
    "Tuvalu",
    "Kiribati",
    "Marshall Islands",
    "Mauritania",
    "Palau",
    "Papua New Guinea",
    "Czech Republic",
    "Turks and Caicos Islands",
    "Western Sahara",
    "Iceland",
    "Monaco",
    "Peru",
    "Qatar",
    "Sweden",
    "Albania",
    "France",
    "Guinea",
    "Zimbabwe",
    "C\u00f4te d'Ivoire",
    "French Polynesia",
    "British Virgin Islands",
    "Christmas Island",
    "Guam",
    "Brunei Darussalam",
    "Equatorial Guinea",
    "Italy",
    "Pakistan",
    "Austria",
    "Comoros",
    "Australia",
    "Kazakhstan",
    "Saint Kitts and Nevis",
    "Haiti",
    "Saint-Martin (French part)",
    "United Arab Emirates",
    "Azerbaijan",
    "Belgium",
    "Guyana",
    "San Marino",
    "Sri Lanka",
    "Anguilla",
    "Bangladesh",
    "New Zealand",
    "Gibraltar",
    "Lithuania",
    "Mongolia",
    "Saint Pierre and Miquelon",
    "Syrian Arab Republic (Syria)",
    "American Samoa",
    "French Guiana",
    "Korea (North)",
    "Korea (South)",
    "Philippines",
    "Tokelau",
    "Venezuela (Bolivarian Republic)",
    "Belize",
    "Benin",
    "Dominican Republic",
    "Dominica",
    "Japan",
    "Moldova",
    "Solomon Islands",
    "Bahamas",
    "Jersey",
    "Latvia",
    "Romania",
    "Russian Federation",
    "Serbia",
    "Singapore",
    "El Salvador",
    "Macao, SAR China",
    "Myanmar",
    "Macedonia, Republic of",
    "Djibouti",
    "Falkland Islands (Malvinas)",
    "Gabon",
    "Lesotho",
    "Malawi",
    "Nauru",
    "Burkina Faso",
    "Burundi",
    "China",
    "Congo (Brazzaville)",
    "Seychelles",
    "Mali",
    "Spain",
    "Zambia",
    "Gambia",
    "Heard and Mcdonald Islands",
    "Samoa",
    "Pitcairn",
    "Sao Tome and Principe",
    "Senegal",
    "South Africa",
    "Central African Republic",
    "Iraq",
    "Luxembourg",
    "Norway",
    "Tunisia",
    "Turkmenistan",
    "Angola",
    "Chile",
    "ALA Aland Islands",
    "Colombia",
    "Puerto Rico",
    "Holy See (Vatican City State)",
    "Republic of Kosovo",
    "Taiwan, Republic of China",
    "Tajikistan",
    "Virgin Islands, US",
    "Ecuador",
    "Greece"
]